export const photographers = [
  {
    id: 'rizki',
    name: 'Rizki Pratama',
    categories: ['wedding', 'event', 'personal', 'sweet17'],
    verified: true,
    og: true,
    specialty: 'Wedding Specialist',
    rating: '4.9',
    sessions: '127',
    response: '<1jam',
    price: 'Rp 400.000/jam',
    priceNum: 400000,
    available: '15 April',
    distance: '1.2 km',
    styles: ['Romantic', 'Candid', 'Outdoor'],
    extraPhotos: 12,
    avatar: 'https://i.pravatar.cc/80?img=11',
  },
  {
    id: 'dinda',
    name: 'Dinda Aulia',
    categories: ['graduation', 'personal', 'event', 'birthday', 'sweet17'],
    verified: true,
    og: false,
    specialty: 'Graduation & Portrait',
    rating: '4.8',
    sessions: '89',
    response: '<2jam',
    price: 'Rp 300.000/jam',
    priceNum: 300000,
    available: '15 April',
    distance: '2.5 km',
    styles: ['Natural', 'Candid', 'Fun'],
    extraPhotos: 8,
    avatar: 'https://i.pravatar.cc/80?img=5',
  },
  {
    id: 'bagas',
    name: 'Bagas Firmansyah',
    categories: ['event', 'corporate', 'graduation'],
    verified: true,
    og: true,
    specialty: 'Event & Corporate',
    rating: '4.7',
    sessions: '203',
    response: '<1jam',
    price: 'Rp 350.000/jam',
    priceNum: 350000,
    available: 'Besok',
    distance: '3.1 km',
    styles: ['Documentary', 'Formal', 'Candid'],
    extraPhotos: 20,
    avatar: 'https://i.pravatar.cc/80?img=8',
  },
  {
    id: 'nadya',
    name: 'Nadya Kusuma',
    categories: ['product', 'food', 'corporate'],
    verified: true,
    og: true,
    specialty: 'Product & Food',
    rating: '4.9',
    sessions: '156',
    response: '<1jam',
    price: 'Rp 280.000/jam',
    priceNum: 280000,
    available: 'Hari Ini',
    distance: '0.8 km',
    styles: ['Minimalist', 'Flat Lay', 'Lifestyle'],
    extraPhotos: 15,
    avatar: 'https://i.pravatar.cc/80?img=25',
  },
  {
    id: 'aldi',
    name: 'Aldi Santoso',
    categories: ['sports-doc', 'event', 'personal'],
    verified: false,
    og: false,
    specialty: 'Event & Personal',
    rating: '4.6',
    sessions: '94',
    response: '<3jam',
    price: 'Rp 320.000/jam',
    priceNum: 320000,
    available: 'Hari Ini',
    distance: '1.5 km',
    styles: ['Dynamic', 'Candid', 'Outdoor'],
    extraPhotos: 9,
    avatar: 'https://i.pravatar.cc/80?img=15',
  },
  {
    id: 'sinta',
    name: 'Sinta Rahayu',
    categories: ['personal', 'graduation', 'food', 'birthday', 'sweet17'],
    verified: true,
    og: false,
    specialty: 'Personal & Graduation',
    rating: '4.8',
    sessions: '112',
    response: '<2jam',
    price: 'Rp 250.000/jam',
    priceNum: 250000,
    available: 'Besok',
    distance: '2.0 km',
    styles: ['Soft', 'Aesthetic', 'Natural'],
    extraPhotos: 11,
    avatar: 'https://i.pravatar.cc/80?img=20',
  },
  {
    id: 'devano',
    name: 'Devano Putra',
    categories: ['wedding', 'personal', 'event'],
    verified: true,
    og: true,
    specialty: 'Wedding & Prewedding',
    rating: '4.9',
    sessions: '178',
    response: '<2jam',
    price: 'Rp 500.000/jam',
    priceNum: 500000,
    available: '15 April',
    distance: '3.4 km',
    styles: ['Cinematic', 'Romantic', 'Elegant'],
    extraPhotos: 18,
    avatar: 'https://i.pravatar.cc/80?img=12',
  },
  {
    id: 'ayu',
    name: 'Ayu Maharani',
    categories: ['event', 'product', 'food', 'birthday'],
    verified: true,
    og: false,
    specialty: 'Event & Product',
    rating: '4.7',
    sessions: '134',
    response: '<2jam',
    price: 'Rp 310.000/jam',
    priceNum: 310000,
    available: 'Hari Ini',
    distance: '1.8 km',
    styles: ['Creative', 'Colorful', 'Lifestyle'],
    extraPhotos: 13,
    avatar: 'https://i.pravatar.cc/80?img=30',
  },
];

export const categoryMeta: Record<string, { name: string; desc: string; subdesc: string; img: string }> = {
  wedding: {
    name: 'Wedding Photography',
    desc: 'Abadikan momen pernikahan terbaik',
    subdesc: 'Fotografer wedding profesional siap membantu',
    img: 'https://picsum.photos/seed/wedding-foto/800/400',
  },
  graduation: {
    name: 'Graduation Photography',
    desc: 'Rayakan wisudamu dengan foto terbaik',
    subdesc: 'Abadikan momen kelulusan bersama orang tersayang',
    img: 'https://picsum.photos/seed/graduation-foto/800/400',
  },
  event: {
    name: 'Event Documentation',
    desc: 'Dokumentasi acara yang profesional',
    subdesc: 'Setiap momen penting terabadikan sempurna',
    img: 'https://picsum.photos/seed/event-foto/800/400',
  },
  product: {
    name: 'Product Photography',
    desc: 'Tampilkan produkmu secara maksimal',
    subdesc: 'Foto produk berkualitas tinggi untuk bisnis kamu',
    img: 'https://picsum.photos/seed/product-foto/800/400',
  },
  food: {
    name: 'Food Photography',
    desc: 'Buat makananmu terlihat menggugah selera',
    subdesc: 'Fotografer food profesional untuk restoran & kuliner',
    img: 'https://picsum.photos/seed/food-foto/800/400',
  },
  corporate: {
    name: 'Corporate Photography',
    desc: 'Tampilan profesional untuk bisnis kamu',
    subdesc: 'Foto korporat, headshot, dan dokumentasi kantor',
    img: 'https://picsum.photos/seed/corporate-foto/800/400',
  },
  personal: {
    name: 'Personal Photoshoot',
    desc: 'Ekspresikan diri dengan foto terbaik',
    subdesc: 'Portrait, lifestyle, dan foto personal berkualitas',
    img: 'https://picsum.photos/seed/personal-foto/800/400',
  },
};

export const homeCategories = [
  { slug: 'wedding',    name: 'Wedding',          img: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=400&h=300&fit=crop' },
  { slug: 'graduation', name: 'Graduation',        img: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=400&h=300&fit=crop' },
  { slug: 'birthday',   name: 'Birthday',          img: 'https://picsum.photos/seed/party/400/300'       },
  { slug: 'sweet17',    name: 'Sweet Seventeen',   img: 'https://picsum.photos/seed/celebration/400/300' },
  { slug: 'event',      name: 'Event',             img: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400&h=300&fit=crop' },
  { slug: 'product',    name: 'Product',           img: 'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=300&fit=crop' },
  { slug: 'food',       name: 'Food',              img: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&h=300&fit=crop' },
  { slug: 'corporate',  name: 'Corporate',         img: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=300&fit=crop' },
  { slug: 'personal',   name: 'Personal',          img: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400&h=300&fit=crop' },
];

export const connectCategories = [
  'Wedding Photography',
  'Graduation Photography',
  'Event Documentation',
  'Product Photography',
  'Food Photography',
  'Corporate Photography',
  'Personal Photoshoot',
];

export type ConnectCategoryConfig = {
  name: string;
  icon: string;
  tagline: string;
  desc: string;
  picsumSeed: string;
  photographerIds: string[];
};

export const connectConfig: Record<string, ConnectCategoryConfig> = {
  wedding: {
    name: 'Wedding Photography',
    icon: '💍',
    tagline: 'Abadikan hari istimewamu',
    desc: 'Abadikan momen pernikahan terbaik',
    picsumSeed: 'wedding-ceremony',
    photographerIds: ['rizki', 'devano'],
  },
  graduation: {
    name: 'Graduation Photography',
    icon: '🎓',
    tagline: 'Momen wisuda tak terlupakan',
    desc: 'Momen wisuda tak terlupakan',
    picsumSeed: 'graduation',
    photographerIds: ['dinda', 'bagas', 'sinta'],
  },
  event: {
    name: 'Event Documentation',
    icon: '🎉',
    tagline: 'Dokumentasi acara profesional',
    desc: 'Dokumentasi acara profesional',
    picsumSeed: 'concert',
    photographerIds: ['bagas', 'ayu', 'rizki'],
  },
  product: {
    name: 'Product Photography',
    icon: '📦',
    tagline: 'Foto produk untuk bisnis online',
    desc: 'Foto produk untuk bisnis online',
    picsumSeed: 'product',
    photographerIds: ['nadya', 'ayu'],
  },
  food: {
    name: 'Food Photography',
    icon: '🍽️',
    tagline: 'Tampilkan menu terbaikmu',
    desc: 'Tampilkan menu terbaikmu',
    picsumSeed: 'food',
    photographerIds: ['nadya', 'sinta', 'ayu'],
  },
  corporate: {
    name: 'Corporate Photography',
    icon: '🏢',
    tagline: 'Foto profesional untuk bisnis',
    desc: 'Foto profesional untuk bisnis',
    picsumSeed: 'office',
    photographerIds: ['bagas', 'nadya'],
  },
  personal: {
    name: 'Personal Photoshoot',
    icon: '🧍',
    tagline: 'Ekspresikan dirimu',
    desc: 'Ekspresikan dirimu',
    picsumSeed: 'portrait',
    photographerIds: ['dinda', 'sinta', 'rizki', 'devano'],
  },
  birthday: {
    name: 'Birthday Photography',
    icon: '🎂',
    tagline: 'Rayakan momen ulang tahunmu',
    desc: 'Rayakan momen ulang tahunmu',
    picsumSeed: 'party',
    photographerIds: ['dinda', 'sinta', 'ayu'],
  },
  sweet17: {
    name: 'Sweet Seventeen Photography',
    icon: '👑',
    tagline: 'Momen sweet seventeen yang berkesan',
    desc: 'Momen sweet seventeen yang berkesan',
    picsumSeed: 'celebration',
    photographerIds: ['dinda', 'sinta', 'rizki'],
  },
};
